### ISSUE TITLE
Server returned HTTP response code: 504 for URL: X

### ISSUE THREAD

**Issue by aistomin** [aistomin/maven-browser#145]
`mvn clean install package` produces:
```
[ERROR] testForLeiningen  Time elapsed: 61.124 s  <<< ERROR!
com.github.aistomin.maven.browser.MvnException: java.io.IOException: Server returned HTTP response code: 504 for URL: https://search.maven.org/solrsearch/select?q=g:com.github.aistomin+AND+a:jenkins-sdk&core=gav&start=0&rows=20&wt=json
	at com.github.aistomin.maven.browser.MavenDependencyTest.dependency(MavenDependencyTest.java:155)
	at com.github.aistomin.maven.browser.MavenDependencyTest.testForLeiningen(MavenDependencyTest.java:143)
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://search.maven.org/solrsearch/select?q=g:com.github.aistomin+AND+a:jenkins-sdk&core=gav&start=0&rows=20&wt=json
	at com.github.aistomin.maven.browser.MavenDependencyTest.dependency(MavenDependencyTest.java:155)
	at com.github.aistomin.maven.browser.MavenDependencyTest.testForLeiningen(MavenDependencyTest.java:143)
```

**Comment by aistomin** [comment]
https://search.maven.org/solrsearch had network issues. I think for such a cases we need to introduce the possibility to temporary switch the validation off.
